---
name: Dependabot automation

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    runs-on: ubuntu-latest
    if: github.action == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.WORKFLOW_TOKEN }}"
      - name: "Enable auto merge"
        run: gh pr merge --auto --squash "${PR_URL}"
